CREATE TABLE "log_entries" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "log_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" varchar(255) NOT NULL,
	"event_type" varchar(100) NOT NULL,
	"call_id" varchar(255) NOT NULL,
	"sequence_number" integer NOT NULL,
	"timestamp" timestamp DEFAULT now(),
	"elapsed_time" real,
	"model" varchar(100),
	"prompt" varchar,
	"response" varchar,
	"agent_type" varchar(50),
	"user_input" varchar,
	"tools_count" integer,
	"max_iterations" integer,
	"tool_name" varchar(100),
	"tool_input" jsonb,
	"tool_output" jsonb,
	"query" varchar,
	"documents_count" integer,
	"documents" jsonb,
	"retriever_type" varchar(100),
	"action" varchar,
	"reasoning" varchar,
	"observation" varchar,
	"error" varchar,
	"error_context" jsonb,
	"llm_parameters" jsonb,
	"llm_usage" jsonb,
	"custom_data" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
